//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp5
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERS
    {
        public int ID_ORDERS { get; set; }
        public int GOODS_ID { get; set; }
        public int BUYERS_ID { get; set; }
    
        public virtual BUYER BUYER { get; set; }
        public virtual GOOD GOOD { get; set; }
    }
}
